name: Build bot on release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Linux Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build in release mode
        run: cargo build --release

      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            target/release/beg_ts_bot